spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
